# Generated by Django 2.0.2 on 2018-11-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180217_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='book',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('black', 'black'), ('white', 'white'), ('grey', 'grey'), ('pruple', 'purple'), ('orange', 'orange')], max_length=2),
        ),
    ]
