# Generated by Django 2.0.2 on 2018-11-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20181103_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('black', 'black'), ('white', 'white'), ('grey', 'grey'), ('pruple', 'purple'), ('orange', 'orange')], max_length=255),
        ),
    ]
